image: maven:latest

#variables:
#  MAVEN_CLI_OPTS: '-s .m2/settings.xml --batch-mode'
#  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'
#
#cache:
#  paths:
#    - .m2/repository/
#    - target/

stages:
  - build
  - test
  - checkstyle
build:
  stage: build
  script:
    - 'echo "Building the client and server"'
    - 'mvn clean package -Dcheckstyle.skip -DskipTests'
test:
  stage: test
  script:
    - 'echo "Testing the client and server"'
    - 'mvn test -Dcheckstyle.skip'
checkstyle:
  stage: checkstyle
  script:
    - 'echo "Executing checkstyle for client and server"'
    - 'mvn validate'